### ISSUE TITLE
Edit profile does not redirect after save

### ISSUE THREAD

**Issue by briri** [DMPRoadmap/roadmap#171]
If you login and edit your profile (e.g. change name) and then click save you are brought to the HTTP 500 server error page.

Logging out and then back in and returning to the profile page shows that the data was saved, so it's likely just an issue with the redirect afterward.

**Comment by briri** [comment]
related to #173

**Comment by briri** [comment]
Is fixed by @jollopre fastgettext changes to the registrations_controller line 112:
https://github.com/DigitalCurationCentre/roadmap/commit/c4d4348c1f976530a5f0c1a66eb4309cbbd634a6#diff-416195ddccbd18a6ce41d5306501765aL112

**Comment by briri** [comment]
closed by accident. should be confirmed once deployed to a server

**Comment by stephaniesimms** [comment]
Not fixed @briri (see error below). I cannot edit/save profile info. When I log out and back in, nothing is updated.

![edit-profile](https://cloud.githubusercontent.com/assets/12703638/24380653/58a05a82-1301-11e7-877a-1326fe45145d.png)
.

**Comment by sjDCC** [comment]
I'm getting same issue. Changes not saved and error displayed. 
![capture](https://cloud.githubusercontent.com/assets/6169940/24516115/80015a14-1571-11e7-86ed-c3084401bc02.PNG)

**Comment by xsrust** [comment]
This error should be fixed by https://github.com/DigitalCurationCentre/roadmap/commit/cb5b0e86e0e1cd4a361d0cd1b2d28b611695a059 and https://github.com/DigitalCurationCentre/roadmap/commit/c2f3e9ce49567251501b22d3d0dcdd69754d26dc

**Comment by stephaniesimms** [comment]
Working as expected
