### ISSUE TITLE
Add 'school/department' field to edit profile page

### ISSUE THREAD

**Issue by sjDCC** [DMPRoadmap/roadmap#2088]
At the two DMPonline user groups, there was a big demand for universities to know which School/Department/Unit their users came from. There is desire to have a question that organisations can define which would be added to the edit profile page under their institution.

Suggested workflow:
Under 'org' page on admin interface, add a tab where this question can be controlled. 
Admin users should be able to specify the label for the field e.g. "School" or "Department"
Admin users should create a controlled value list as a dropdown or checkbox
This should display as a combobox

On the front end "edit profile' page, end users should see this question beneath their organisation field. If the organisation has not set the entry, then no question will show.

Make this field editable for admins e.g. on the user page view an admin has

**Comment by xsrust** [comment]
I suggest that we add a new model for a 'department' with users having one department and orgs having many.  
Org-admins can define additional departements, and change the label for their org on what they want to call these sub-groupings.

For-now, it shouldbe sufficient just to:
- allow org-admins to define the list from the edit-org-details page
- allow users (who's organisations have defined the groupings) to select from their org's list on edit-profile
- display this category in the users table of the org/super admin interfaces
- Remove this attribute when the user changes organisation

down the line, when we add more functionality to this (i.e. only reviewers of the same department get notified) may want to re-factor this so that the user gains their org through the 'department'.
I think if we do the association correctly, and generate a 'main' or 'generic' `department` for all the existing orgs, we would not need to re-write the selection logic for `user.org` anywhere in the tool.

I'm hesitant to make the department such an integral object immediately though

**Comment by johnpinto1** [comment]
@xsrust @briri I found a bug for the current scenario.

- As **Org admin**, go to **Organisation details** page and create**  a **school/department** for your **org**, say **Chemistry** in 
- Go to **Edit profile** page and add **Chemistry**  as a school/department for a user
-  Now as **Org admin**, go to **Organisation details** page and delete the **school/department**  **Chemistry**

I am a way of deleting the **department_id** from users for **Chemistry** when I delete it.

**Comment by johnpinto1** [comment]
@xsrust @briri Found a fix in this blog https://til.hashrocket.com/posts/jqilnp3d0h--set-foreign-keys-to-null
Will push a new PR soon.

**Comment by johnpinto1** [comment]
Steps to test once last PR accepted:
- Log in as an **Org admin**.
- Go to **Organistaion details** page and select **School/Department** tab
- Initially, the page will be empty
- Add some school or departments (some without codes). See this link for examples from Durham University
https://www.dur.ac.uk/cis/email/lists/options/depts/
- Got to  you will find the * and select a  **school/department** and save. (Note: **school/department** option will only be visible if the **organistaion** has data added).
- Now go to **Organistaion details** page and select **School/Department**
- Under actions you trying edit and removing **school/department**. 
- In particular, remove the **school/department** you added to the user. In this case, when you return to **Edit profile** you will find **school/department** empty.

Some screen shoots to help:
![Selection_019](https://user-images.githubusercontent.com/8876215/58955039-c1541980-8792-11e9-8b55-0b3f32a88563.png)
![Selection_017](https://user-images.githubusercontent.com/8876215/58955089-e2b50580-8792-11e9-91a8-4cb57487fc21.png)

![Selection_025](https://user-images.githubusercontent.com/8876215/58955300-8acace80-8793-11e9-9140-069407cfa71e.png)
![Select](https://user-images.githubusercontent.com/8876215/58955806-c619cd00-8794-11e9-9191-dbe510e79443.png)

**Comment by johnpinto1** [comment]
@xsrust and @briri sorry about this but I noticed the dropdown Department list was not ordered. So have another PR.

**Comment by johnpinto1** [comment]
@briri and @xsrust Just realised translations not catered for. Will look at that after June 17th.

**Comment by sjDCC** [comment]
Hi @johnpinto1 This is looking good - thanks.

I spotted a few things which need amendments.

1. When I have been affiliated with a uni which has departments and then change to another without, I see this field greyed out. It would be better not to see the field at all in my opinion as it's confusing to have no options.
![Capture](https://user-images.githubusercontent.com/6169940/59286526-cec44480-8c67-11e9-8914-f30cc7511e42.PNG)

2. I added and removed departments and this worked fine when I was an org admin but not as a super-admin. When I added depts to Aberystwyth as a super-admin, these got added to Glasgow (the org my super-admin account is affiliated with). Could you ensure that super-admin changes inherent values from which org they click to edit, not which they are affiliated with. This bug will be an edge case, but there will always be a few super-admins

3. Also as a super-admin, when I tried to edit or remove a School/Dept I got an unauthorised warning. Super-admins should have permissions to change any org
![Capture](https://user-images.githubusercontent.com/6169940/59286847-65910100-8c68-11e9-8288-3fe23e33c13e.PNG)

4. When I changed my org-admin account from Aberystwyth to Institute of Science and Technology Information (INIST in France), I lost admin permissions as expected, but the Department affiliation remained in the user table. INIST doesn't have departments added so this data is invalid. My profile page now shows Depts greyed out with nothing in the dropdown, but the admin users table still shows an affiliation. This column of the table shouldn't show when there isn't data to display.
![Capture](https://user-images.githubusercontent.com/6169940/59287001-adb02380-8c68-11e9-8d1a-cce92bfa76be.PNG)

**Comment by johnpinto1** [comment]
@sjDCC **1** above is an easy fix.
I have spoken to @xsrust  about **2-4**. He has given me some pointers. I will clarify if the changes I make with both of you before proceeding.

**Comment by johnpinto1** [comment]
@sjDCC @xsrust  I have just pushed code following @xsrust suggestions which should address the issues cited by @sjDCC **1-4**:

- Department policies now allow both org admins and super admins to create update and delete departments, whilst org_admins can only do this for their own org. Super admins can do it for any org department.
-When a super admin switches organisation their department_id is cleared.

**Comment by sjDCC** [comment]
Hi @johnpinto1 I'm still getting an issue with this. The workflow is as follows as a super-admin:

1. I click 'Organisations' to view all orgs and select one to edit. I picked Aber
![1](https://user-images.githubusercontent.com/6169940/59853254-6280c980-9368-11e9-906a-c5c830d1ad7b.PNG)

2. I go to the 'Departments' tab and see what content is there. I'm still seeing Aber at this point

3. I click to 'Create school or department' and get taken to a new window. At this point it seems to lose stickiness to Aber. 
![0 1](https://user-images.githubusercontent.com/6169940/59853455-d02cf580-9368-11e9-8aa4-7b1bf080f0dd.PNG)

4. When I add a school/dept and go back to view them I am taken to my organisational affiliation. In effect, super-admins can't control which org they are adding content to. See all the test entries against Glasgow
![2](https://user-images.githubusercontent.com/6169940/59853604-1b470880-9369-11e9-8668-605114736fb1.PNG)


I think the error may come as there is no 'super-admin switching panel on the first page like with the template editing. See screengrab below.
![Capture](https://user-images.githubusercontent.com/6169940/59853721-5b0df000-9369-11e9-82d7-f92a52226566.PNG)

**Comment by xsrust** [comment]
I had a quick look at the code.
It looks like the department's org_id is set based on the user's org on both the create:
https://github.com/DMPRoadmap/roadmap/blob/development/app/controllers/org_admin/departments_controller.rb#L19
and update:
https://github.com/DMPRoadmap/roadmap/blob/development/app/controllers/org_admin/departments_controller.rb#L42
@johnpinto1 
I think if you were to add a hidden 'org_id' field to the edit page, and assign org_id based on that
and then expand the auth logic used for edit/update/destroy:
https://github.com/DMPRoadmap/roadmap/blob/development/app/policies/department_policy.rb#L23-L24
to cover the create action as well.

I think it would be better to keep the editing as-is, rather than adding in the org-switcher & making super-admins update their organisation before changing an org's details, especially as editing the existing org-details does not require the switcher.

**Comment by johnpinto1** [comment]
@sjDCC @xsrust Thanks for the pointers on what needs done. Will attempt to get changes done tomorrow.

**Comment by magdalenadrafiova** [comment]
This all works perfectly. Closing out

**Comment by magdalenadrafiova** [comment]
@mariapraetzellis have a look - Sarah and I tested this and we were happy with this but feel free to have a look yourself and if it is good let us know and we can deploy :)

**Comment by mariapraetzellis** [comment]
@magdalenadrafiova- Brian and I took a look at this yesterday and it looked good. Thanks!
