### ISSUE TITLE
Unable to add notifications on questions in a new template

### ISSUE THREAD

**Issue by mariapraetzellis** [DMPRoadmap/roadmap#2637]
When creating a new template I am unable to add a notification condition on a question. The feature seems to get stuck on the "removes" conditional option, but does not allow for the creation of a notification rule. For example, editing this template: https://dmponline-test.dcc.ac.uk/org_admin/templates/6275/phases/7522/edit?section=44808

![screenshot-dmponline-test dcc ac uk-2020 08 17-15_44_24](https://user-images.githubusercontent.com/27511575/90451626-15e66a80-e0a1-11ea-8e34-a752c874c409.png)

**Comment by raycarrick-ed** [comment]
fixed in
https://github.com/DMPRoadmap/roadmap/tree/issue_2637
bootstrap-select wasn't being added.

**Comment by mariapraetzellis** [comment]
I am now able to add a notification to a question. I didn't check to make sure it sends emails yet since I think we're still having issues with sending emails.

**Comment by mariapraetzellis** [comment]
I added a notification successfully (to plan https://dmponline-test.dcc.ac.uk/plans/56072), but upon filling out the plan I did not get the email notification. I did get the visual notification w/in the plan that a trigger was in place: "This answer triggers email(s) to mariapraetzellis@pm.me"

**Comment by raycarrick-ed** [comment]
Tested with new mail catcher and looks like it works ok.
